config/routes.rb
Rails.application.routes.draw do
 get 'tops/main'
 post 'tops/login'
 root 'tops#main'
 get 'tops/logout'
 resources :users, only:[:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    validates :uid, uniqueness: true
    def self.authenticate(uid,pass)
        if user = find_by(uid,pass:pass)
            user
        else
            nil
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def L4
      session[:c]||= 0
      session[:c] = session[:c].to_i + 1
      render plain:session[:c]
      session[:login_uid]
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def main
    if session[:login_uid]
      render 'main'
    else
      render 'login'
    end
  end

  def login
    if User.find_by(uid:params[:uid], pass:params[:pass])
        session[:login_uid] = params[:uid]
        redirect_to tops_main_path
    else
        render 'error'
    end
  end
   def logout
       session.delete(:login_uid)
       redirect_to tops_main_path
   end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index,
  end

  def new,
  end

  def create,
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    def new
        @user = User.new
    end
    def create
         pass = BCrypt::Password.create(params[:user][:pass])
         @user = User.new(uid: params[:user][:uid], pass: pass)
        if @user.save
            
            flash[:success] = "登録完了"
            redirect_to users_path
        else
            flash[:failed] = "登録失敗"
            render 'new'
        end
    end
    def destroy 
        user = User.find(params[:id])
        user.destroy
            flash[:destroy] = "削除しました。"
        redirect_to users_path, flash: {destroy:  "ツイートを削除しました。"}
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L4</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tops/error.html.erb
<p>ログイン失敗</p>

<%= link_to 'Back', tops_main_path %>

app/views/tops/login.html.erb
<h2>ログイン画面</h2>
<% if flash[:notice] %>
  <p><font color="blue"><%= flash[:notice] %></font></p>
<% end %>  
<%= form_tag '/tops/login', method: :post do %>
  <%= label_tag :uid, 'ユーザーID' %>
  <%= text_field_tag :uid %>
  <%= label_tag :pass, 'パスワード' %>
  <%= password_field_tag :pass %>
  <%= submit_tag 'ログイン' %>
<% end %>  
<%= link_to "新規登録", new_user_path %>
<%= link_to "ユーザー情報", users_path %>

app/views/tops/main.html.erb
<h2>MY PAGE</h2>
<p><font color="blue">ログイン中です</font></p>

<%= link_to "ログアウト", tops_logout_path %>

app/views/users/index.html.erb
<h2>ユーザー</h2>

<% @users.each do |user| %>
 <p>
     <%= user.uid %>
     <%= user.pass %>
     <%= link_to 'delete', user, method: :delete %>
 </p>
<% end %>
<%= link_to "ログイン", tops_main_path %>

<%= link_to "新規登録", new_user_path %>

app/views/users/new.html.erb
<h2>新規登録画面</h2>
<%= form_for @user do |form| %>
 <%= form.label :uid, "ユーザーID" %>
 <%= form.text_field :uid %>
 <%= form.label :pass, "パスワード" %>
 <%= form.password_field :pass %>
 <%= form.submit "登録" %>
<% end %>

<%= link_to 'Back', tops_main_path %>